'use strict'

const ROLES = {
  SUPER_ADMIN      : 'SUPER_ADMIN',
  ADMIN            : 'ADMIN',
  COMMERCIAL_ADMIN : 'COMMERCIAL_ADMIN',
  CUSTOMER_SERVICE : 'CUSTOMER_SERVICE',
  AREA_MANAGER     : 'AREA_MANAGER',
  REGIONAL_MANAGER : 'REGIONAL_MANAGER',
  DIVISION_MANAGER : 'DIVISION_MANAGER',
  SALES_DIRECTOR   : 'SALES_DIRECTOR',
  MANAGING_DIRECTOR: 'MANAGING_DIRECTOR'
}

const VALID_ROLES = Object.values(ROLES)
const MAX_ROLES   = 3

const STATUS = { PENDING: 'PENDING', ACTIVE: 'ACTIVE', INACTIVE: 'INACTIVE' }

const MATRIX_ROLE_MAP = {
  sales_owner_id : ROLES.AREA_MANAGER,
  rm_id          : ROLES.REGIONAL_MANAGER,
  dm_id          : ROLES.DIVISION_MANAGER,
  sd_id          : ROLES.SALES_DIRECTOR,
  md_id          : ROLES.MANAGING_DIRECTOR
}
const MATRIX_SLOTS = Object.keys(MATRIX_ROLE_MAP)

const AUDIT = {
  USER_REGISTERED    : 'USER_REGISTERED',
  USER_APPROVED      : 'USER_APPROVED',
  USER_ROLES_UPDATED : 'USER_ROLES_UPDATED',
  USER_DEACTIVATED   : 'USER_DEACTIVATED',
  USER_REACTIVATED   : 'USER_REACTIVATED',
  MATRIX_CREATED     : 'MATRIX_CREATED',
  MATRIX_CLOSED      : 'MATRIX_CLOSED',
  BUDGET_CREATED     : 'BUDGET_CREATED',
  BUDGET_UPDATED     : 'BUDGET_UPDATED',
  BUDGET_IMPORTED    : 'BUDGET_IMPORTED',
  PRODUCT_CREATED    : 'PRODUCT_CREATED',
  PRODUCT_UPDATED    : 'PRODUCT_UPDATED',
  PRODUCT_DEACTIVATED: 'PRODUCT_DEACTIVATED',
  PRODUCT_REACTIVATED: 'PRODUCT_REACTIVATED',
  FAMILY_CREATED     : 'FAMILY_CREATED',
  FAMILY_UPDATED     : 'FAMILY_UPDATED',
  FAMILY_DEACTIVATED : 'FAMILY_DEACTIVATED',
  FAMILY_REACTIVATED : 'FAMILY_REACTIVATED',
  MAPPING_CREATED    : 'MAPPING_CREATED',
  MAPPING_REMOVED    : 'MAPPING_REMOVED',
  IMPORT_JOB_CREATED   : 'IMPORT_JOB_CREATED',
  IMPORT_JOB_COMMITTED : 'IMPORT_JOB_COMMITTED',
  IMPORT_JOB_CANCELLED : 'IMPORT_JOB_CANCELLED',
  MATRIX_PUBLISHED      : 'MATRIX_PUBLISHED',
  DELEGATION_CREATED   : 'DELEGATION_CREATED',
  DELEGATION_DEACTIVATED: 'DELEGATION_DEACTIVATED',
  USER_POSITION_UPDATED : 'USER_POSITION_UPDATED',
  USER_MANAGER_UPDATED  : 'USER_MANAGER_UPDATED',
  USER_RANK_UPDATED     : 'USER_RANK_UPDATED'
}

const PRODUCT_STATUS = {
  ACTIVE   : 'ACTIVE',
  INACTIVE : 'INACTIVE'
}

const MAPPING_SOURCE = {
  MANUAL : 'MANUAL',
  IMPORT : 'IMPORT'
}

const IMPORT_FILE_TYPE = {
  PRODUCT  : 'PRODUCT',
  CUSTOMER : 'CUSTOMER',
  SHIP_TO          : 'SHIP_TO',
  HISTORICAL_SALES : 'HISTORICAL_SALES'
}

const IMPORT_MODULE_NAME = {
  PRODUCT  : 'Product Registry',
  CUSTOMER : 'Customer Registry',
  SHIP_TO          : 'Ship-To Registry',
  HISTORICAL_SALES : 'Historical Sales'
}

const IMPORT_PRIMARY_KEY_FIELD = {
  PRODUCT  : 'product_code',
  CUSTOMER : 'customerCode',
  SHIP_TO  : 'shipToCode'
}

const IMPORT_JOB_STATUS = {
  PENDING             : 'PENDING',
  STAGED              : 'STAGED',
  VALIDATED           : 'VALIDATED',
  COMMITTED           : 'COMMITTED',
  PARTIALLY_COMMITTED : 'PARTIALLY_COMMITTED',
  CANCELLED           : 'CANCELLED',
  FAILED              : 'FAILED'
}

const VALIDATION_STATUS = {
  OK       : 'OK',
  CONFLICT : 'CONFLICT',
  ERROR    : 'ERROR'
}

const USER_DECISION = {
  SKIP          : 'SKIP',
  UPDATE        : 'UPDATE',
  MANUAL_REVIEW : 'MANUAL_REVIEW'
}

const COMMIT_STATUS = {
  PENDING    : 'PENDING',
  PROCESSING : 'PROCESSING',
  COMMITTED  : 'COMMITTED'
}

const CLEANUP_STATUS = {
  ACTIVE  : 'ACTIVE',
  EXPIRED : 'EXPIRED'
}

const VALID_POSITIONS = [
  'AREA_MANAGER',
  'REGIONAL_MANAGER',
  'DIVISION_MANAGER',
  'SALES_DIRECTOR',
  'MANAGING_DIRECTOR'
]
const AUTHORITY_RANK = {
  MANAGING_DIRECTOR : 'Managing Director',
  SALES_DIRECTOR    : 'Sales Director',
  DIVISION_MANAGER  : 'Division Manager',
  SALES_MANAGER     : 'Sales Manager',
  AREA_MANAGER      : 'Area Manager',
}
const VALID_AUTHORITY_RANKS = Object.values(AUTHORITY_RANK)

module.exports = {
  ROLES,
  VALID_ROLES,
  MAX_ROLES,
  STATUS,
  MATRIX_ROLE_MAP,
  MATRIX_SLOTS,
  AUDIT,
  PRODUCT_STATUS,
  MAPPING_SOURCE,
  IMPORT_FILE_TYPE,
  IMPORT_MODULE_NAME,
  IMPORT_PRIMARY_KEY_FIELD,
  IMPORT_JOB_STATUS,
  VALIDATION_STATUS,
  USER_DECISION,
  COMMIT_STATUS,
  CLEANUP_STATUS,
  VALID_POSITIONS,
  AUTHORITY_RANK,
  VALID_AUTHORITY_RANKS,
}
