'use strict'
const ROLES = {
  SUPER_ADMIN      : 'SUPER_ADMIN',
  ADMIN            : 'ADMIN',
  COMMERCIAL_ADMIN : 'COMMERCIAL_ADMIN',
  CUSTOMER_SERVICE : 'CUSTOMER_SERVICE',
  AREA_MANAGER     : 'AREA_MANAGER',
  REGIONAL_MANAGER : 'REGIONAL_MANAGER',
  DIVISION_MANAGER : 'DIVISION_MANAGER',
  SALES_DIRECTOR   : 'SALES_DIRECTOR',
  MANAGING_DIRECTOR: 'MANAGING_DIRECTOR'
}
const VALID_ROLES = Object.values(ROLES)
const MAX_ROLES = 3
const STATUS = { PENDING: 'PENDING', ACTIVE: 'ACTIVE', INACTIVE: 'INACTIVE' }
const MATRIX_ROLE_MAP = {
  sales_owner_id : ROLES.AREA_MANAGER,
  rm_id          : ROLES.REGIONAL_MANAGER,
  dm_id          : ROLES.DIVISION_MANAGER,
  sd_id          : ROLES.SALES_DIRECTOR,
  md_id          : ROLES.MANAGING_DIRECTOR
}
const MATRIX_SLOTS = Object.keys(MATRIX_ROLE_MAP)
const AUDIT = {
  USER_REGISTERED    : 'USER_REGISTERED',
  USER_APPROVED      : 'USER_APPROVED',
  USER_ROLES_UPDATED : 'USER_ROLES_UPDATED',
  USER_DEACTIVATED   : 'USER_DEACTIVATED',
  USER_REACTIVATED   : 'USER_REACTIVATED',
  MATRIX_CREATED     : 'MATRIX_CREATED',
  MATRIX_CLOSED      : 'MATRIX_CLOSED'
}
module.exports = { ROLES, VALID_ROLES, MAX_ROLES, STATUS, MATRIX_ROLE_MAP, MATRIX_SLOTS, AUDIT }
