'use strict'

// Portal-specific status enums — ISOLATED from FCOS STATUS
const CUSTOMER_USER_STATUS = {
  INVITED   : 'INVITED',
  ACTIVE    : 'ACTIVE',
  SUSPENDED : 'SUSPENDED'
}

const INVITATION_STATUS = {
  PENDING  : 'PENDING',
  ACCEPTED : 'ACCEPTED',
  EXPIRED  : 'EXPIRED'
}

const PORTAL_AUDIT = {
  CUSTOMER_USER_INVITED        : 'CUSTOMER_USER_INVITED',
  CUSTOMER_USER_ACTIVATED      : 'CUSTOMER_USER_ACTIVATED',
  CUSTOMER_USER_SUSPENDED      : 'CUSTOMER_USER_SUSPENDED',
  CUSTOMER_INVITATION_CREATED  : 'CUSTOMER_INVITATION_CREATED',
  CUSTOMER_INVITATION_ACCEPTED : 'CUSTOMER_INVITATION_ACCEPTED'
}

module.exports = { CUSTOMER_USER_STATUS, INVITATION_STATUS, PORTAL_AUDIT }
